### ISSUE TITLE
Object movement 

### ISSUE THREAD

**Issue by matrxs** [matrxs/MATRXS#3]
How should objects move in the new html frontend. This can be done in a number of methods: 

1. As is done now, update the position (e.g. absolute position x y value) of an object 60 times per second and moving it x pixels. Advantage is that existing code can be used, and that precise movements can be executed on screen. Disadvantage is that dom-interactions are costly, such that updating potentially hundreds of objects 60x per second is going to be slow (bu how slow?).
2.  Use CSS animations. This is much easier, as only the goal position has to be given, and a time on how long it should take to animate that change. Open issue with this again is the speed, how fast is this for hundreds of objects at high tick speeds?

**Comment by jwaa** [comment]
Not my expertise really, but I would say that we go for the 2nd. It may be some additional work, but simpler seems te be more maintainable. Also, native css animations sound more optimized than random code we copied from the internet... But could be wrong here :)

@thaije If you made a decision, please open a new issue for that solution, refer to it here in a comment and close this.

**Comment by thaije** [comment]
Default front-end now uses css animations for movement of objects.
